# Generated by Django 5.0.4 on 2024-10-31 15:25
import random

from django.db import migrations, models


class Migration(migrations.Migration):


    def generate_barcodes(apps, schema_editor):
        Product = apps.get_model('main_app', 'Product')
        all_products = Product.objects.all()
        barcodes = random.sample(range(10000000, 1000000000), len(all_products))
        for product, barcode in zip(all_products, barcodes):
            product.barcode = barcode
            product.save()

    def reverse_barcodes(apps, schema_editor):
        Product = apps.get_model('main_app', 'Product')
        for product in Product.objects.all():
            product.barcode = 0
            product.save()


    dependencies = [
        ('main_app', '0005_product_barcode')
    ]

    operations = [
        migrations.RunPython(generate_barcodes, reverse_barcodes)
    ]

